### ISSUE TITLE
Incompatibility with Enhanced Block Entities Mod

### ISSUE THREAD

**Issue by iijj22gg** [StartsMercury/simply-no-shading#83]
I've noticed this mod is incompatible with the [Enhanced Block Entities Mod](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities). The game doesn't crash, but all block entities render as missing blocks.

Here's a link to a screenshot:
https://drive.google.com/file/d/1NvDyE4ep4i_3OZ_E4i-YZLbvLHB6Cfgh/view?usp=sharing

The error that appears several times in my logs:
```Mixin apply for mod simply-no-shading failed simply-no-shading+fabric.mixins.json:shading.enhanced.block.entity.enhancedblockentities.DynamicBakedModelFabricMixin from mod simply-no-shading -> foundationgames.enhancedblockentities.client.model.DynamicBakedModel: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Redirect annotation on initEmittedBlockQuads could not find any targets matching 'Lfoundationgames/enhancedblockentities/client/model/DynamicBakedModel;emitBlockQuads(Lnet/minecraft/class_1920;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Ljava/util/function/Supplier;Ljava/lang/Object;)V' in foundationgames.enhancedblockentities.client.model.DynamicBakedModel. Using refmap simply-no-shading-refmap.json [PREINJECT Applicator Phase -> simply-no-shading+fabric.mixins.json:shading.enhanced.block.entity.enhancedblockentities.DynamicBakedModelFabricMixin from mod simply-no-shading -> Prepare Injections ->  -> redirect$ccl000$initEmittedBlockQuads(Ljava/util/Iterator;)Ljava/lang/Object; -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on initEmittedBlockQuads could not find any targets matching 'Lfoundationgames/enhancedblockentities/client/model/DynamicBakedModel;emitBlockQuads(Lnet/minecraft/class_1920;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Ljava/util/function/Supplier;Ljava/lang/Object;)V' in foundationgames.enhancedblockentities.client.model.DynamicBakedModel. Using refmap simply-no-shading-refmap.json [PREINJECT Applicator Phase -> simply-no-shading+fabric.mixins.json:shading.enhanced.block.entity.enhancedblockentities.DynamicBakedModelFabricMixin from mod simply-no-shading -> Prepare Injections ->  -> redirect$ccl000$initEmittedBlockQuads(Ljava/util/Iterator;)Ljava/lang/Object; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44)
	at jdk.internal.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at foundationgames.enhancedblockentities.client.model.DynamicUnbakedModel.method_4753(DynamicUnbakedModel.java:45)
	at net.minecraft.class_1088.method_15878(class_1088.java:481)
	at net.minecraft.class_807.method_4753(class_807.java:77)
	at net.minecraft.class_1088.method_15878(class_1088.java:481)
	at net.minecraft.class_1088.method_4733(class_1088.java:250)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at net.minecraft.class_1088.method_18177(class_1088.java:247)
	at net.minecraft.class_1092.method_18179(class_1092.java:67)
	at net.minecraft.class_1092.method_18788(class_1092.java:19)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.Complehttps://www.curseforge.com/minecraft/mc-mods/enhanced-block-entitiestableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:211)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by StartsMercury** [comment]
May I know if this is still an issue in the pre-releases of 5.1.0?

**Comment by iijj22gg** [comment]
I'll check it out sometime next month, I need to get a new mouse so I can actually play Minecraft

**Comment by StartsMercury** [comment]
I see. Anyways I wasn't able to test the mod myself before my previous comment and I noticed it to be buggy... Though I haven't had an issue with EBE, well in the development environment at least.

**Comment by iijj22gg** [comment]
Alright, I'm using 1.19.3 now, but EBE hasn't updated yet. I'll give it a shot when that mod updates.

**Comment by ASIICTIVE** [comment]
Is there any updates on this? I'm running into an incompability issue with the same mod, except my game crashes on boot and gives exit code -1.
Using Simply No Shading 5.0.4 with EBE 0.7.2

**Comment by StartsMercury** [comment]
For 1.19.3: Simply No Shading 6.0.0-pre.4 and EBE 0.8 are compatible.

**Comment by ASIICTIVE** [comment]
> 

Any possibility of a 1.19.2 fix?

**Comment by StartsMercury** [comment]
I'll try when I've got the time.

**Comment by StartsMercury** [comment]
~~6.0.3~~ 6.0.7 for Minecraft 1.19.2 is live! Let me know if it works.
